# CMake generated Testfile for 
# Source directory: D:/projects/brogameagent/tests
# Build directory: D:/projects/brogameagent/build_cuda/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[brogameagent_test]=] "D:/projects/brogameagent/build_cuda/tests/Debug/brogameagent_test.exe")
  set_tests_properties([=[brogameagent_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;13;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[brogameagent_test]=] "D:/projects/brogameagent/build_cuda/tests/Release/brogameagent_test.exe")
  set_tests_properties([=[brogameagent_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;13;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[brogameagent_test]=] "D:/projects/brogameagent/build_cuda/tests/MinSizeRel/brogameagent_test.exe")
  set_tests_properties([=[brogameagent_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;13;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[brogameagent_test]=] "D:/projects/brogameagent/build_cuda/tests/RelWithDebInfo/brogameagent_test.exe")
  set_tests_properties([=[brogameagent_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;13;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
else()
  add_test([=[brogameagent_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[brogameagent_transformer_test]=] "D:/projects/brogameagent/build_cuda/tests/Debug/brogameagent_transformer_test.exe")
  set_tests_properties([=[brogameagent_transformer_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;25;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[brogameagent_transformer_test]=] "D:/projects/brogameagent/build_cuda/tests/Release/brogameagent_transformer_test.exe")
  set_tests_properties([=[brogameagent_transformer_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;25;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[brogameagent_transformer_test]=] "D:/projects/brogameagent/build_cuda/tests/MinSizeRel/brogameagent_transformer_test.exe")
  set_tests_properties([=[brogameagent_transformer_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;25;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[brogameagent_transformer_test]=] "D:/projects/brogameagent/build_cuda/tests/RelWithDebInfo/brogameagent_transformer_test.exe")
  set_tests_properties([=[brogameagent_transformer_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;25;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
else()
  add_test([=[brogameagent_transformer_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[brogameagent_adam_test]=] "D:/projects/brogameagent/build_cuda/tests/Debug/brogameagent_adam_test.exe")
  set_tests_properties([=[brogameagent_adam_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;37;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[brogameagent_adam_test]=] "D:/projects/brogameagent/build_cuda/tests/Release/brogameagent_adam_test.exe")
  set_tests_properties([=[brogameagent_adam_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;37;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[brogameagent_adam_test]=] "D:/projects/brogameagent/build_cuda/tests/MinSizeRel/brogameagent_adam_test.exe")
  set_tests_properties([=[brogameagent_adam_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;37;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[brogameagent_adam_test]=] "D:/projects/brogameagent/build_cuda/tests/RelWithDebInfo/brogameagent_adam_test.exe")
  set_tests_properties([=[brogameagent_adam_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;37;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
else()
  add_test([=[brogameagent_adam_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[brogameagent_single_hero_net_tx_test]=] "D:/projects/brogameagent/build_cuda/tests/Debug/brogameagent_single_hero_net_tx_test.exe")
  set_tests_properties([=[brogameagent_single_hero_net_tx_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;49;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[brogameagent_single_hero_net_tx_test]=] "D:/projects/brogameagent/build_cuda/tests/Release/brogameagent_single_hero_net_tx_test.exe")
  set_tests_properties([=[brogameagent_single_hero_net_tx_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;49;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[brogameagent_single_hero_net_tx_test]=] "D:/projects/brogameagent/build_cuda/tests/MinSizeRel/brogameagent_single_hero_net_tx_test.exe")
  set_tests_properties([=[brogameagent_single_hero_net_tx_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;49;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[brogameagent_single_hero_net_tx_test]=] "D:/projects/brogameagent/build_cuda/tests/RelWithDebInfo/brogameagent_single_hero_net_tx_test.exe")
  set_tests_properties([=[brogameagent_single_hero_net_tx_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;49;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
else()
  add_test([=[brogameagent_single_hero_net_tx_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[brogameagent_gpu_tensor_test]=] "D:/projects/brogameagent/build_cuda/tests/Debug/brogameagent_gpu_tensor_test.exe")
  set_tests_properties([=[brogameagent_gpu_tensor_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;62;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[brogameagent_gpu_tensor_test]=] "D:/projects/brogameagent/build_cuda/tests/Release/brogameagent_gpu_tensor_test.exe")
  set_tests_properties([=[brogameagent_gpu_tensor_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;62;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[brogameagent_gpu_tensor_test]=] "D:/projects/brogameagent/build_cuda/tests/MinSizeRel/brogameagent_gpu_tensor_test.exe")
  set_tests_properties([=[brogameagent_gpu_tensor_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;62;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[brogameagent_gpu_tensor_test]=] "D:/projects/brogameagent/build_cuda/tests/RelWithDebInfo/brogameagent_gpu_tensor_test.exe")
  set_tests_properties([=[brogameagent_gpu_tensor_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;62;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
else()
  add_test([=[brogameagent_gpu_tensor_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[brogameagent_gpu_linear_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/Debug/brogameagent_gpu_linear_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_linear_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[brogameagent_gpu_linear_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/Release/brogameagent_gpu_linear_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_linear_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[brogameagent_gpu_linear_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/MinSizeRel/brogameagent_gpu_linear_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_linear_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[brogameagent_gpu_linear_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/RelWithDebInfo/brogameagent_gpu_linear_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_linear_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
else()
  add_test([=[brogameagent_gpu_linear_parity_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[brogameagent_gpu_elementwise_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/Debug/brogameagent_gpu_elementwise_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_elementwise_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[brogameagent_gpu_elementwise_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/Release/brogameagent_gpu_elementwise_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_elementwise_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[brogameagent_gpu_elementwise_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/MinSizeRel/brogameagent_gpu_elementwise_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_elementwise_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[brogameagent_gpu_elementwise_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/RelWithDebInfo/brogameagent_gpu_elementwise_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_elementwise_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
else()
  add_test([=[brogameagent_gpu_elementwise_parity_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[brogameagent_gpu_softmax_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/Debug/brogameagent_gpu_softmax_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_softmax_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[brogameagent_gpu_softmax_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/Release/brogameagent_gpu_softmax_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_softmax_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[brogameagent_gpu_softmax_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/MinSizeRel/brogameagent_gpu_softmax_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_softmax_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[brogameagent_gpu_softmax_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/RelWithDebInfo/brogameagent_gpu_softmax_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_softmax_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
else()
  add_test([=[brogameagent_gpu_softmax_parity_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[brogameagent_gpu_layernorm_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/Debug/brogameagent_gpu_layernorm_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_layernorm_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[brogameagent_gpu_layernorm_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/Release/brogameagent_gpu_layernorm_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_layernorm_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[brogameagent_gpu_layernorm_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/MinSizeRel/brogameagent_gpu_layernorm_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_layernorm_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[brogameagent_gpu_layernorm_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/RelWithDebInfo/brogameagent_gpu_layernorm_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_layernorm_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
else()
  add_test([=[brogameagent_gpu_layernorm_parity_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[brogameagent_gpu_attention_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/Debug/brogameagent_gpu_attention_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_attention_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[brogameagent_gpu_attention_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/Release/brogameagent_gpu_attention_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_attention_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[brogameagent_gpu_attention_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/MinSizeRel/brogameagent_gpu_attention_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_attention_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[brogameagent_gpu_attention_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/RelWithDebInfo/brogameagent_gpu_attention_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_attention_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
else()
  add_test([=[brogameagent_gpu_attention_parity_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[brogameagent_gpu_optim_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/Debug/brogameagent_gpu_optim_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_optim_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[brogameagent_gpu_optim_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/Release/brogameagent_gpu_optim_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_optim_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[brogameagent_gpu_optim_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/MinSizeRel/brogameagent_gpu_optim_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_optim_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[brogameagent_gpu_optim_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/RelWithDebInfo/brogameagent_gpu_optim_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_optim_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
else()
  add_test([=[brogameagent_gpu_optim_parity_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[brogameagent_gpu_adam_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/Debug/brogameagent_gpu_adam_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_adam_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[brogameagent_gpu_adam_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/Release/brogameagent_gpu_adam_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_adam_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[brogameagent_gpu_adam_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/MinSizeRel/brogameagent_gpu_adam_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_adam_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[brogameagent_gpu_adam_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/RelWithDebInfo/brogameagent_gpu_adam_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_adam_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
else()
  add_test([=[brogameagent_gpu_adam_parity_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[brogameagent_gpu_reduce_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/Debug/brogameagent_gpu_reduce_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_reduce_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[brogameagent_gpu_reduce_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/Release/brogameagent_gpu_reduce_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_reduce_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[brogameagent_gpu_reduce_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/MinSizeRel/brogameagent_gpu_reduce_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_reduce_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[brogameagent_gpu_reduce_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/RelWithDebInfo/brogameagent_gpu_reduce_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_reduce_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
else()
  add_test([=[brogameagent_gpu_reduce_parity_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[brogameagent_gpu_loss_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/Debug/brogameagent_gpu_loss_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_loss_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[brogameagent_gpu_loss_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/Release/brogameagent_gpu_loss_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_loss_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[brogameagent_gpu_loss_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/MinSizeRel/brogameagent_gpu_loss_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_loss_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[brogameagent_gpu_loss_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/RelWithDebInfo/brogameagent_gpu_loss_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_loss_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
else()
  add_test([=[brogameagent_gpu_loss_parity_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[brogameagent_gpu_embedding_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/Debug/brogameagent_gpu_embedding_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_embedding_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[brogameagent_gpu_embedding_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/Release/brogameagent_gpu_embedding_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_embedding_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[brogameagent_gpu_embedding_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/MinSizeRel/brogameagent_gpu_embedding_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_embedding_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[brogameagent_gpu_embedding_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/RelWithDebInfo/brogameagent_gpu_embedding_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_embedding_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
else()
  add_test([=[brogameagent_gpu_embedding_parity_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[brogameagent_gpu_concat_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/Debug/brogameagent_gpu_concat_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_concat_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[brogameagent_gpu_concat_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/Release/brogameagent_gpu_concat_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_concat_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[brogameagent_gpu_concat_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/MinSizeRel/brogameagent_gpu_concat_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_concat_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[brogameagent_gpu_concat_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/RelWithDebInfo/brogameagent_gpu_concat_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_concat_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
else()
  add_test([=[brogameagent_gpu_concat_parity_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[brogameagent_gpu_mha_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/Debug/brogameagent_gpu_mha_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_mha_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[brogameagent_gpu_mha_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/Release/brogameagent_gpu_mha_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_mha_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[brogameagent_gpu_mha_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/MinSizeRel/brogameagent_gpu_mha_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_mha_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[brogameagent_gpu_mha_parity_test]=] "D:/projects/brogameagent/build_cuda/tests/RelWithDebInfo/brogameagent_gpu_mha_parity_test.exe")
  set_tests_properties([=[brogameagent_gpu_mha_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;90;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
else()
  add_test([=[brogameagent_gpu_mha_parity_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[brogameagent_gpu_layer_layernorm_dispatch_test]=] "D:/projects/brogameagent/build_cuda/tests/Debug/brogameagent_gpu_layer_layernorm_dispatch_test.exe")
  set_tests_properties([=[brogameagent_gpu_layer_layernorm_dispatch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;115;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[brogameagent_gpu_layer_layernorm_dispatch_test]=] "D:/projects/brogameagent/build_cuda/tests/Release/brogameagent_gpu_layer_layernorm_dispatch_test.exe")
  set_tests_properties([=[brogameagent_gpu_layer_layernorm_dispatch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;115;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[brogameagent_gpu_layer_layernorm_dispatch_test]=] "D:/projects/brogameagent/build_cuda/tests/MinSizeRel/brogameagent_gpu_layer_layernorm_dispatch_test.exe")
  set_tests_properties([=[brogameagent_gpu_layer_layernorm_dispatch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;115;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[brogameagent_gpu_layer_layernorm_dispatch_test]=] "D:/projects/brogameagent/build_cuda/tests/RelWithDebInfo/brogameagent_gpu_layer_layernorm_dispatch_test.exe")
  set_tests_properties([=[brogameagent_gpu_layer_layernorm_dispatch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;115;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
else()
  add_test([=[brogameagent_gpu_layer_layernorm_dispatch_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[brogameagent_gpu_layer_layernorm_adam_dispatch_test]=] "D:/projects/brogameagent/build_cuda/tests/Debug/brogameagent_gpu_layer_layernorm_adam_dispatch_test.exe")
  set_tests_properties([=[brogameagent_gpu_layer_layernorm_adam_dispatch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;115;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[brogameagent_gpu_layer_layernorm_adam_dispatch_test]=] "D:/projects/brogameagent/build_cuda/tests/Release/brogameagent_gpu_layer_layernorm_adam_dispatch_test.exe")
  set_tests_properties([=[brogameagent_gpu_layer_layernorm_adam_dispatch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;115;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[brogameagent_gpu_layer_layernorm_adam_dispatch_test]=] "D:/projects/brogameagent/build_cuda/tests/MinSizeRel/brogameagent_gpu_layer_layernorm_adam_dispatch_test.exe")
  set_tests_properties([=[brogameagent_gpu_layer_layernorm_adam_dispatch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;115;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[brogameagent_gpu_layer_layernorm_adam_dispatch_test]=] "D:/projects/brogameagent/build_cuda/tests/RelWithDebInfo/brogameagent_gpu_layer_layernorm_adam_dispatch_test.exe")
  set_tests_properties([=[brogameagent_gpu_layer_layernorm_adam_dispatch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;115;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
else()
  add_test([=[brogameagent_gpu_layer_layernorm_adam_dispatch_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[brogameagent_gpu_layer_attention_dispatch_test]=] "D:/projects/brogameagent/build_cuda/tests/Debug/brogameagent_gpu_layer_attention_dispatch_test.exe")
  set_tests_properties([=[brogameagent_gpu_layer_attention_dispatch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;115;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[brogameagent_gpu_layer_attention_dispatch_test]=] "D:/projects/brogameagent/build_cuda/tests/Release/brogameagent_gpu_layer_attention_dispatch_test.exe")
  set_tests_properties([=[brogameagent_gpu_layer_attention_dispatch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;115;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[brogameagent_gpu_layer_attention_dispatch_test]=] "D:/projects/brogameagent/build_cuda/tests/MinSizeRel/brogameagent_gpu_layer_attention_dispatch_test.exe")
  set_tests_properties([=[brogameagent_gpu_layer_attention_dispatch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;115;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[brogameagent_gpu_layer_attention_dispatch_test]=] "D:/projects/brogameagent/build_cuda/tests/RelWithDebInfo/brogameagent_gpu_layer_attention_dispatch_test.exe")
  set_tests_properties([=[brogameagent_gpu_layer_attention_dispatch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;115;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
else()
  add_test([=[brogameagent_gpu_layer_attention_dispatch_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[brogameagent_gpu_layer_mha_dispatch_test]=] "D:/projects/brogameagent/build_cuda/tests/Debug/brogameagent_gpu_layer_mha_dispatch_test.exe")
  set_tests_properties([=[brogameagent_gpu_layer_mha_dispatch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;115;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[brogameagent_gpu_layer_mha_dispatch_test]=] "D:/projects/brogameagent/build_cuda/tests/Release/brogameagent_gpu_layer_mha_dispatch_test.exe")
  set_tests_properties([=[brogameagent_gpu_layer_mha_dispatch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;115;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[brogameagent_gpu_layer_mha_dispatch_test]=] "D:/projects/brogameagent/build_cuda/tests/MinSizeRel/brogameagent_gpu_layer_mha_dispatch_test.exe")
  set_tests_properties([=[brogameagent_gpu_layer_mha_dispatch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;115;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[brogameagent_gpu_layer_mha_dispatch_test]=] "D:/projects/brogameagent/build_cuda/tests/RelWithDebInfo/brogameagent_gpu_layer_mha_dispatch_test.exe")
  set_tests_properties([=[brogameagent_gpu_layer_mha_dispatch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;115;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
else()
  add_test([=[brogameagent_gpu_layer_mha_dispatch_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[brogameagent_gpu_layer_feedforward_dispatch_test]=] "D:/projects/brogameagent/build_cuda/tests/Debug/brogameagent_gpu_layer_feedforward_dispatch_test.exe")
  set_tests_properties([=[brogameagent_gpu_layer_feedforward_dispatch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;115;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[brogameagent_gpu_layer_feedforward_dispatch_test]=] "D:/projects/brogameagent/build_cuda/tests/Release/brogameagent_gpu_layer_feedforward_dispatch_test.exe")
  set_tests_properties([=[brogameagent_gpu_layer_feedforward_dispatch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;115;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[brogameagent_gpu_layer_feedforward_dispatch_test]=] "D:/projects/brogameagent/build_cuda/tests/MinSizeRel/brogameagent_gpu_layer_feedforward_dispatch_test.exe")
  set_tests_properties([=[brogameagent_gpu_layer_feedforward_dispatch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;115;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[brogameagent_gpu_layer_feedforward_dispatch_test]=] "D:/projects/brogameagent/build_cuda/tests/RelWithDebInfo/brogameagent_gpu_layer_feedforward_dispatch_test.exe")
  set_tests_properties([=[brogameagent_gpu_layer_feedforward_dispatch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;115;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
else()
  add_test([=[brogameagent_gpu_layer_feedforward_dispatch_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[brogameagent_gpu_layer_transformer_block_dispatch_test]=] "D:/projects/brogameagent/build_cuda/tests/Debug/brogameagent_gpu_layer_transformer_block_dispatch_test.exe")
  set_tests_properties([=[brogameagent_gpu_layer_transformer_block_dispatch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;115;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[brogameagent_gpu_layer_transformer_block_dispatch_test]=] "D:/projects/brogameagent/build_cuda/tests/Release/brogameagent_gpu_layer_transformer_block_dispatch_test.exe")
  set_tests_properties([=[brogameagent_gpu_layer_transformer_block_dispatch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;115;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[brogameagent_gpu_layer_transformer_block_dispatch_test]=] "D:/projects/brogameagent/build_cuda/tests/MinSizeRel/brogameagent_gpu_layer_transformer_block_dispatch_test.exe")
  set_tests_properties([=[brogameagent_gpu_layer_transformer_block_dispatch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;115;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[brogameagent_gpu_layer_transformer_block_dispatch_test]=] "D:/projects/brogameagent/build_cuda/tests/RelWithDebInfo/brogameagent_gpu_layer_transformer_block_dispatch_test.exe")
  set_tests_properties([=[brogameagent_gpu_layer_transformer_block_dispatch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;115;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
else()
  add_test([=[brogameagent_gpu_layer_transformer_block_dispatch_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[brogameagent_gpu_layer_transformer_encoder_dispatch_test]=] "D:/projects/brogameagent/build_cuda/tests/Debug/brogameagent_gpu_layer_transformer_encoder_dispatch_test.exe")
  set_tests_properties([=[brogameagent_gpu_layer_transformer_encoder_dispatch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;115;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[brogameagent_gpu_layer_transformer_encoder_dispatch_test]=] "D:/projects/brogameagent/build_cuda/tests/Release/brogameagent_gpu_layer_transformer_encoder_dispatch_test.exe")
  set_tests_properties([=[brogameagent_gpu_layer_transformer_encoder_dispatch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;115;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[brogameagent_gpu_layer_transformer_encoder_dispatch_test]=] "D:/projects/brogameagent/build_cuda/tests/MinSizeRel/brogameagent_gpu_layer_transformer_encoder_dispatch_test.exe")
  set_tests_properties([=[brogameagent_gpu_layer_transformer_encoder_dispatch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;115;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[brogameagent_gpu_layer_transformer_encoder_dispatch_test]=] "D:/projects/brogameagent/build_cuda/tests/RelWithDebInfo/brogameagent_gpu_layer_transformer_encoder_dispatch_test.exe")
  set_tests_properties([=[brogameagent_gpu_layer_transformer_encoder_dispatch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;115;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
else()
  add_test([=[brogameagent_gpu_layer_transformer_encoder_dispatch_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[brogameagent_gpu_layer_autoencoder_dispatch_test]=] "D:/projects/brogameagent/build_cuda/tests/Debug/brogameagent_gpu_layer_autoencoder_dispatch_test.exe")
  set_tests_properties([=[brogameagent_gpu_layer_autoencoder_dispatch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;115;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[brogameagent_gpu_layer_autoencoder_dispatch_test]=] "D:/projects/brogameagent/build_cuda/tests/Release/brogameagent_gpu_layer_autoencoder_dispatch_test.exe")
  set_tests_properties([=[brogameagent_gpu_layer_autoencoder_dispatch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;115;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[brogameagent_gpu_layer_autoencoder_dispatch_test]=] "D:/projects/brogameagent/build_cuda/tests/MinSizeRel/brogameagent_gpu_layer_autoencoder_dispatch_test.exe")
  set_tests_properties([=[brogameagent_gpu_layer_autoencoder_dispatch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;115;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[brogameagent_gpu_layer_autoencoder_dispatch_test]=] "D:/projects/brogameagent/build_cuda/tests/RelWithDebInfo/brogameagent_gpu_layer_autoencoder_dispatch_test.exe")
  set_tests_properties([=[brogameagent_gpu_layer_autoencoder_dispatch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;115;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
else()
  add_test([=[brogameagent_gpu_layer_autoencoder_dispatch_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[brogameagent_gpu_single_hero_net_tx_dispatch_test]=] "D:/projects/brogameagent/build_cuda/tests/Debug/brogameagent_gpu_single_hero_net_tx_dispatch_test.exe")
  set_tests_properties([=[brogameagent_gpu_single_hero_net_tx_dispatch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;115;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[brogameagent_gpu_single_hero_net_tx_dispatch_test]=] "D:/projects/brogameagent/build_cuda/tests/Release/brogameagent_gpu_single_hero_net_tx_dispatch_test.exe")
  set_tests_properties([=[brogameagent_gpu_single_hero_net_tx_dispatch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;115;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[brogameagent_gpu_single_hero_net_tx_dispatch_test]=] "D:/projects/brogameagent/build_cuda/tests/MinSizeRel/brogameagent_gpu_single_hero_net_tx_dispatch_test.exe")
  set_tests_properties([=[brogameagent_gpu_single_hero_net_tx_dispatch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;115;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[brogameagent_gpu_single_hero_net_tx_dispatch_test]=] "D:/projects/brogameagent/build_cuda/tests/RelWithDebInfo/brogameagent_gpu_single_hero_net_tx_dispatch_test.exe")
  set_tests_properties([=[brogameagent_gpu_single_hero_net_tx_dispatch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/projects/brogameagent/tests/CMakeLists.txt;115;add_test;D:/projects/brogameagent/tests/CMakeLists.txt;0;")
else()
  add_test([=[brogameagent_gpu_single_hero_net_tx_dispatch_test]=] NOT_AVAILABLE)
endif()
